# Generated by Django 4.2.1 on 2024-06-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0025_cracking_extraction_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer_info',
            name='parish',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
