# Generated by Django 4.2.1 on 2024-06-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0026_farmer_info_parish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer_info',
            old_name='parish',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='parish',
            new_name='address',
        ),
        migrations.AddField(
            model_name='land_info',
            name='altitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='land_info',
            name='parish',
            field=models.CharField(choices=[('', '--Select an option--'), ('Saint Andrew', 'Saint Andrew'), ('Saint David', 'Saint David'), ('Saint George', 'Saint George'), ('Saint John', 'Saint John'), ('Saint Mark', 'Saint Mark'), ('Saint Patrick', 'Saint Patrick')], max_length=50, null=True),
        ),
    ]
